#!/usr/bin/env python3
"""synthetic.py — seeded synthetic record generators for PRISM-C PL4 tests.

Fully deterministic (SEED = 20260702), no API calls. Generates the record
kinds the estimator consumes (stated / need / choice incl. controls) with
planted structure: known conditional-logit weights, planted divergence,
dominating positive controls, symmetric negative controls.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from prism_c_lib import arrangements  # noqa: E402

SEED = 20260702
OPS = ["OP1", "OP2", "OP3", "OP4"]
CHANNELS = ["official", "press", "experience", "social"]
FAMILIES = {
    "CH-ANT": "anthropic",
    "CH-OAI": "openai",
    "CH-ALI": "alibaba",
    "CH-DSK": "deepseek",
}
DIMENSIONS = [
    "semiotic",
    "narrative",
    "ideological",
    "experiential",
    "social",
    "economic",
    "cultural",
    "temporal",
]


def synth_brands(n: int = 10, rng: np.random.Generator | None = None) -> dict:
    rng = rng or np.random.default_rng(SEED)
    return {f"Brand{i:02d}": np.clip(rng.uniform(1.5, 9.5, 8), 0, 10) for i in range(n)}


def synth_scenarios(
    brands: dict,
    n_scenarios: int = 12,
    set_size: int = 4,
    rng: np.random.Generator | None = None,
) -> list[dict]:
    rng = rng or np.random.default_rng(SEED + 1)
    names = sorted(brands)
    out = []
    for i in range(n_scenarios):
        cset = sorted(rng.choice(names, size=set_size, replace=False).tolist())
        out.append(
            {
                "id": f"T{i:02d}",
                "sector": "b2c" if i % 2 == 0 else "b2b",
                "choice_set": cset,
                "need_vec": np.clip(rng.uniform(1.0, 9.5, 8), 0, 10),
            }
        )
    return out


def stated_records(
    profiles: dict, noise: float = 0.15, rng: np.random.Generator | None = None
) -> list[dict]:
    rng = rng or np.random.default_rng(SEED + 2)
    rows = []
    for brand, prof in profiles.items():
        for op in OPS:
            for ch in CHANNELS:
                rows.append(
                    {
                        "kind": "stated",
                        "brand": brand,
                        "coherence_type": "synthetic",
                        "sector": "b2c",
                        "goods_type": "experience",
                        "channel": ch,
                        "op_pair": op,
                        "readout": "dims",
                        "value": np.clip(
                            prof + rng.normal(0, noise, 8), 0, 10
                        ).tolist(),
                        "flagged_malformed": False,
                        "prompt_version": "prism-c/synthetic",
                    }
                )
    return rows


def need_records(
    scenarios: list[dict],
    noise: float = 0.1,
    rng: np.random.Generator | None = None,
) -> list[dict]:
    rng = rng or np.random.default_rng(SEED + 3)
    rows = []
    for sc in scenarios:
        for op in OPS:
            rows.append(
                {
                    "kind": "need",
                    "scenario": sc["id"],
                    "sector": sc["sector"],
                    "op_pair": op,
                    "readout": "dims",
                    "value": np.clip(
                        sc["need_vec"] + rng.normal(0, noise, 8), 0, 10
                    ).tolist(),
                    "flagged_malformed": False,
                    "prompt_version": "prism-c/synthetic",
                }
            )
    return rows


def _choice_row(sc, arr, arr_id, chooser, family, pick, control=None, dominant=None):
    return {
        "kind": "choice",
        "scenario": sc["id"],
        "sector": sc.get("sector"),
        "choice_set": sorted(arr),
        "arrangement": list(arr),
        "arrangement_id": arr_id,
        "chooser": chooser,
        "family": family,
        "model": f"synthetic-{family}",
        "pick": pick,
        "ranking": None,
        "flagged_malformed": False,
        "control": control,
        "dominant": dominant,
        "prompt_version": "prism-c/synthetic",
    }


def choice_records_cl(
    scenarios: list[dict],
    profiles: dict,
    beta: np.ndarray,
    *,
    position_boost: float = 0.0,
    gumbel_scale: float = 0.0,
    rng: np.random.Generator | None = None,
    n_arrangements: int = 8,
) -> list[dict]:
    """Choices generated by a conditional-logit utility with known weights:
    U_j = beta . (-|brand_j - need| / 10) + position_boost * 1[pos=0]
    (+ Gumbel noise if gumbel_scale > 0; deterministic argmax otherwise)."""
    rng = rng or np.random.default_rng(SEED + 4)
    rows = []
    for sc in scenarios:
        for arr_id, arr in enumerate(arrangements(sc["choice_set"], n_arrangements)):
            for chooser, family in FAMILIES.items():
                us = []
                for pos, b in enumerate(arr):
                    x = -np.abs(profiles[b] - sc["need_vec"]) / 10.0
                    u = float(beta @ x) + (position_boost if pos == 0 else 0.0)
                    if gumbel_scale > 0:
                        u += float(rng.gumbel(0, gumbel_scale))
                    us.append(u)
                pick = arr[int(np.argmax(us))]
                rows.append(_choice_row(sc, arr, arr_id, chooser, family, pick))
    return rows


def choice_records_predicted(
    scenarios: list[dict], profiles: dict, *, n_arrangements: int = 8
) -> list[dict]:
    """No-gap data: every family always picks the cosine-nearest brand to the
    need vector (the predicted pick). H1 must come out unsupported."""

    def cos(a, b):
        return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))

    rows = []
    for sc in scenarios:
        pred = max(sc["choice_set"], key=lambda b: cos(profiles[b], sc["need_vec"]))
        for arr_id, arr in enumerate(arrangements(sc["choice_set"], n_arrangements)):
            for chooser, family in FAMILIES.items():
                rows.append(_choice_row(sc, arr, arr_id, chooser, family, pred))
    return rows


def positive_control_records(*, obey: bool = True) -> list[dict]:
    """Five dominating-option sets; if obey, every chooser picks the dominant
    brand (control must PASS); else the first-listed option (must FAIL)."""
    rows = []
    for i in range(5):
        sc = {"id": f"P{i:02d}", "sector": "control"}
        opts = [f"Dominant{i}", f"FillerA{i}", f"FillerB{i}"]
        for arr_id, arr in enumerate(arrangements(opts, 8)):
            for chooser, family in FAMILIES.items():
                pick = f"Dominant{i}" if obey else arr[0]
                rows.append(
                    _choice_row(
                        sc,
                        arr,
                        arr_id,
                        chooser,
                        family,
                        pick,
                        control="positive",
                        dominant=f"Dominant{i}",
                    )
                )
    return rows


def negative_control_records(
    *, biased: bool = False, rng: np.random.Generator | None = None
) -> list[dict]:
    """Five near-duplicate twin sets; if biased, every chooser prefers twin A
    regardless of position (control must FAIL); else the pick follows the
    first-listed position (position residue only - counterbalanced across the
    two arrangements this yields a 50/50 split per set, control must PASS)."""
    rows = []
    for i in range(5):
        sc = {"id": f"N{i:02d}", "sector": "control"}
        opts = [f"TwinA{i}", f"TwinB{i}"]
        for arr_id, arr in enumerate(arrangements(opts, 8)):
            for chooser, family in FAMILIES.items():
                pick = f"TwinA{i}" if biased else arr[0]
                rows.append(
                    _choice_row(
                        sc, arr, arr_id, chooser, family, pick, control="negative"
                    )
                )
    return rows
